### ISSUE TITLE
Infografía_Gestión de Requisitos.

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-1-infografia-yanet-02-1#1]
[Infografia_Yanet Gonzalez Garcia..pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-yanet-02-1/files/14308593/Infografia_Yanet.Gonzalez.Garcia.pdf)

**Comment by ka194** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
